Search.setIndex({
  alltitles: {
    "API Docs": [[1, null]],
    "Additional Code Information": [[2, "additional-code-information"]],
    "Arguments:": [
      [0, "arguments"],
      [0, "id1"],
    ],
    Authors: [[3, "authors"]],
    "Basic Use": [[2, null]],
    "General Code Usage": [[2, "general-code-usage"]],
    PyCosmoMMF: [[3, null]],
    "Returns:": [
      [0, "returns"],
      [0, "id2"],
    ],
    "Step I": [[2, "step-i"]],
    "Step II": [[2, "step-ii"]],
    Submodules: [[0, "submodules"]],
    "pycosmommf package": [[0, null]],
    "pycosmommf.filter module": [[0, "module-pycosmommf.filter"]],
    "pycosmommf.hessian module": [[0, "module-pycosmommf.hessian"]],
    "pycosmommf.signatures module": [[0, "module-pycosmommf.signatures"]],
    "pycosmommf.tagging module": [[0, "module-pycosmommf.tagging"]],
    "pycosmommf.utils module": [[0, "module-pycosmommf.utils"]],
  },
  docnames: ["api/pycosmommf", "api_tab", "basic_usage", "index"],
  envversion: {
    sphinx: 64,
    "sphinx.domains.c": 3,
    "sphinx.domains.changeset": 1,
    "sphinx.domains.citation": 1,
    "sphinx.domains.cpp": 9,
    "sphinx.domains.index": 1,
    "sphinx.domains.javascript": 3,
    "sphinx.domains.math": 2,
    "sphinx.domains.python": 4,
    "sphinx.domains.rst": 2,
    "sphinx.domains.std": 2,
    "sphinx.ext.intersphinx": 1,
  },
  filenames: ["api/pycosmommf.rst", "api_tab.md", "basic_usage.md", "index.md"],
  indexentries: {
    "calc_mass_change() (in module pycosmommf.tagging)": [
      [0, "pycosmommf.tagging.calc_mass_change", false],
    ],
    "calc_structure_bools() (in module pycosmommf.tagging)": [
      [0, "pycosmommf.tagging.calc_structure_bools", false],
    ],
    "cylinder() (in module pycosmommf.utils)": [
      [0, "pycosmommf.utils.cylinder", false],
    ],
    "fast_hessian_from_smoothed() (in module pycosmommf.hessian)": [
      [0, "pycosmommf.hessian.fast_hessian_from_smoothed", false],
    ],
    "kspace_gaussian_filter() (in module pycosmommf.filter)": [
      [0, "pycosmommf.filter.kspace_gaussian_filter", false],
    ],
    "kspace_top_hat_filter() (in module pycosmommf.filter)": [
      [0, "pycosmommf.filter.kspace_top_hat_filter", false],
    ],
    "make_the_clusbool() (in module pycosmommf.tagging)": [
      [0, "pycosmommf.tagging.make_the_clusbool", false],
    ],
    "maximum_signature() (in module pycosmommf.signatures)": [
      [0, "pycosmommf.signatures.maximum_signature", false],
    ],
    module: [
      [0, "module-pycosmommf", false],
      [0, "module-pycosmommf.filter", false],
      [0, "module-pycosmommf.hessian", false],
      [0, "module-pycosmommf.signatures", false],
      [0, "module-pycosmommf.tagging", false],
      [0, "module-pycosmommf.utils", false],
    ],
    pycosmommf: [[0, "module-pycosmommf", false]],
    "pycosmommf.filter": [[0, "module-pycosmommf.filter", false]],
    "pycosmommf.hessian": [[0, "module-pycosmommf.hessian", false]],
    "pycosmommf.signatures": [[0, "module-pycosmommf.signatures", false]],
    "pycosmommf.tagging": [[0, "module-pycosmommf.tagging", false]],
    "pycosmommf.utils": [[0, "module-pycosmommf.utils", false]],
    "shrink() (in module pycosmommf.utils)": [
      [0, "pycosmommf.utils.shrink", false],
    ],
    "signatures_from_hessian() (in module pycosmommf.signatures)": [
      [0, "pycosmommf.signatures.signatures_from_hessian", false],
    ],
    "smooth_gauss() (in module pycosmommf.filter)": [
      [0, "pycosmommf.filter.smooth_gauss", false],
    ],
    "smooth_loggauss() (in module pycosmommf.filter)": [
      [0, "pycosmommf.filter.smooth_loggauss", false],
    ],
    "smooth_top_hat() (in module pycosmommf.filter)": [
      [0, "pycosmommf.filter.smooth_top_hat", false],
    ],
    "sphere() (in module pycosmommf.utils)": [
      [0, "pycosmommf.utils.sphere", false],
    ],
    "wall() (in module pycosmommf.utils)": [
      [0, "pycosmommf.utils.wall", false],
    ],
    "wavevectors3d() (in module pycosmommf.filter)": [
      [0, "pycosmommf.filter.wavevectors3D", false],
    ],
  },
  objects: {
    "": [[0, 0, 0, "-", "pycosmommf"]],
    pycosmommf: [
      [0, 0, 0, "-", "filter"],
      [0, 0, 0, "-", "hessian"],
      [0, 0, 0, "-", "signatures"],
      [0, 0, 0, "-", "tagging"],
      [0, 0, 0, "-", "utils"],
    ],
    "pycosmommf.filter": [
      [0, 1, 1, "", "kspace_gaussian_filter"],
      [0, 1, 1, "", "kspace_top_hat_filter"],
      [0, 1, 1, "", "smooth_gauss"],
      [0, 1, 1, "", "smooth_loggauss"],
      [0, 1, 1, "", "smooth_top_hat"],
      [0, 1, 1, "", "wavevectors3D"],
    ],
    "pycosmommf.hessian": [[0, 1, 1, "", "fast_hessian_from_smoothed"]],
    "pycosmommf.signatures": [
      [0, 1, 1, "", "maximum_signature"],
      [0, 1, 1, "", "signatures_from_hessian"],
    ],
    "pycosmommf.tagging": [
      [0, 1, 1, "", "calc_mass_change"],
      [0, 1, 1, "", "calc_structure_bools"],
      [0, 1, 1, "", "make_the_clusbool"],
    ],
    "pycosmommf.utils": [
      [0, 1, 1, "", "cylinder"],
      [0, 1, 1, "", "shrink"],
      [0, 1, 1, "", "sphere"],
      [0, 1, 1, "", "wall"],
    ],
  },
  objnames: {
    0: ["py", "module", "Python module"],
    1: ["py", "function", "Python function"],
  },
  objtypes: { 0: "py:module", 1: "py:function" },
  terms: {
    "": 0,
    0: [0, 2],
    "08": 0,
    1: [0, 2],
    10: 2,
    "1d": 0,
    "1e": 0,
    2: [0, 2],
    200: [0, 2],
    2013: 2,
    2022: 2,
    2024: 0,
    283185307179586: 0,
    3: 0,
    370: [0, 2],
    "3d": 0,
    4: 2,
    "4d": [0, 2],
    "4th": 2,
    500: [0, 2],
    6: 0,
    8: 0,
    A: 0,
    For: 2,
    In: 2,
    On: 2,
    The: [0, 2],
    accomplish: 0,
    achiev: 2,
    across: [0, 2],
    adrian: 3,
    al: 2,
    alg: [0, 2],
    algorithm: [0, 2],
    all: [0, 2],
    allow: 0,
    also: 2,
    an: [0, 2],
    analysi: 2,
    analyz: 2,
    anoth: 2,
    appli: [0, 2],
    ar: [0, 2],
    argument: 2,
    arrai: [0, 2],
    avail: 2,
    avoid: 0,
    baryon: 2,
    base: 2,
    bayer: 3,
    being: 2,
    below: 2,
    berkelei: 3,
    besid: 2,
    best: 2,
    block: 0,
    boolean: [0, 2],
    box: 0,
    box_siz: 0,
    build: 0,
    c: 0,
    calc_mass_chang: 0,
    calc_structure_bool: [0, 2],
    calcul: [0, 2],
    can: [0, 2],
    categor: 2,
    categori: 2,
    cautun: 2,
    cca: 3,
    center: 0,
    chang: [0, 2],
    clusbool: [0, 2],
    clusbool_ext: 2,
    cluster: [0, 2],
    cluster_boolean_filt: 2,
    collaps: [0, 2],
    come: 0,
    commonli: 0,
    comput: [0, 2],
    contain: [0, 2],
    copyright: 0,
    correspond: 2,
    cosmic: [0, 2, 3],
    cosmolog: [0, 2],
    cosmommf: 0,
    creat: 0,
    criteria: 2,
    criterion: 2,
    curv: [0, 2],
    cylind: 0,
    data: [0, 2],
    debug: 2,
    default: [0, 2],
    delta: 0,
    delta_vec: 0,
    denot: 2,
    densiti: 2,
    density_field: 2,
    depend: 2,
    describ: 2,
    detect: 2,
    determin: [0, 2],
    dict: 0,
    dictionari: 0,
    differ: 2,
    dim: 0,
    dimens: 0,
    divis: 0,
    dm2_fil: [0, 2],
    dm2_wall: [0, 2],
    document: 0,
    doe: 2,
    download: 2,
    each: [0, 2],
    effect: 2,
    eigenvalu: 2,
    either: 0,
    entir: 2,
    ep: 0,
    error: 0,
    et: 2,
    etc: 2,
    exampl: 2,
    extern: 2,
    f: 0,
    f_rn: 0,
    f_vir_clu: 0,
    fals: 2,
    fast_hessian_from_smooth: 0,
    few: 2,
    field: [0, 2, 3],
    filament: [0, 2],
    filbool: [0, 2],
    filter: 2,
    filter_k: 0,
    find: [0, 2],
    finder: 2,
    first: 2,
    flag: [0, 2],
    float: [0, 2],
    fof: 2,
    follow: 0,
    formal: 2,
    fraction: 0,
    from: [0, 2, 3],
    function: [0, 2],
    gaussian: [0, 2],
    give: 2,
    given: [0, 3],
    gott: 0,
    greater: 2,
    grid: [0, 2],
    gunn: 0,
    h: 2,
    halo: 2,
    hat: 0,
    have: 2,
    help: [0, 2],
    hessian: 2,
    highli: 2,
    i: [0, 3],
    identifi: [0, 3],
    illustristng: 2,
    implement: 2,
    import: 2,
    index: [1, 2],
    insid: 2,
    instead: 2,
    int: 0,
    ipmu: 3,
    jame: [0, 3],
    jia: 3,
    julia: 2,
    k: 0,
    kavli: 3,
    kei: 0,
    kspace_gaussian_filt: 0,
    kspace_top_hat_filt: 0,
    kv: 0,
    kx: 0,
    ky: 0,
    kz: 0,
    li: 3,
    like: 2,
    link: 2,
    liu: 3,
    load: 2,
    log: 0,
    logarithm: 2,
    look: [0, 2],
    lot: 2,
    make: 2,
    make_the_clusbool: 0,
    mass: [0, 2],
    matrix: [0, 2],
    matter: 2,
    max_sig: 0,
    max_signatur: 2,
    maximum: [0, 2],
    maximum_signatur: [0, 2],
    mean: 2,
    method: 2,
    minimum: 0,
    mmf: 2,
    modifi: 2,
    modul: 1,
    more: [0, 2],
    morpholog: 2,
    motiv: [0, 2],
    mpc: 2,
    multipl: 2,
    multiscal: 2,
    n: [0, 2],
    necessari: 2,
    new_siz: 0,
    nexu: [0, 2],
    nexusplu: [0, 2],
    none: 0,
    note: 2,
    np: 2,
    npy: 2,
    number: 0,
    nxnxn: 0,
    off: 2,
    one: 2,
    onli: [0, 2],
    option: [0, 2],
    other: [0, 2],
    our: 2,
    out: 0,
    output: 2,
    over: [0, 2],
    overdens: [0, 2, 3],
    own: 2,
    packag: [2, 3],
    page: 1,
    paper: [0, 2],
    paramet: [0, 2],
    path: 2,
    physic: [0, 2],
    pipelin: 2,
    plot: 2,
    point: 0,
    princeton: 3,
    produc: 2,
    product: 2,
    provid: 2,
    purpos: 2,
    pycosmommf: 2,
    python: 2,
    r: [0, 2],
    r_: 0,
    r_200: [0, 2],
    r_500: [0, 2],
    radiu: 0,
    rang: 2,
    refer: 0,
    reserv: 0,
    resolut: 2,
    resolv: 2,
    rest: 0,
    result: 2,
    right: 0,
    rockstar: 2,
    roughli: 2,
    run: 2,
    s_clu: 0,
    s_fil: [0, 2],
    s_wall: [0, 2],
    scale: [0, 2],
    scheme: 2,
    search: 1,
    second: 2,
    see: 2,
    seen: 2,
    select: 0,
    set: [0, 2],
    sever: 2,
    shrink: 0,
    sig: 0,
    sig_vec: 0,
    sigmax: 0,
    signatur: 2,
    signatures_from_hessian: 0,
    simpl: 0,
    simul: 2,
    size: 0,
    small: 0,
    smax: 0,
    smin: 0,
    smooth: [0, 2],
    smooth_gauss: 0,
    smooth_loggauss: 0,
    smooth_top_hat: 0,
    so: 2,
    space: 0,
    specif: 2,
    sphere: 0,
    spheric: 0,
    spuriou: 2,
    sqrt: 2,
    start: 2,
    streamlin: 2,
    string: 0,
    structur: [0, 2, 3],
    sum: 0,
    summar: 2,
    summary_data: 0,
    sunseri: [0, 2, 3],
    tag: 2,
    than: 2,
    thei: 2,
    thi: [0, 2],
    thought: 2,
    threshold: [0, 2],
    tool: 2,
    top: 0,
    true: 2,
    trust: 2,
    tupl: 0,
    turn: 2,
    two: 2,
    type: [0, 2],
    uc: 3,
    us: 0,
    utokyo: 3,
    valu: [0, 2],
    verbos: [0, 2],
    verbose_flag: 2,
    version: 2,
    virial: [0, 2],
    void: [0, 2],
    voidbool: [0, 2],
    voxel: 2,
    wai: 2,
    wall: [0, 2],
    wallbool: [0, 2],
    want: 2,
    wavevector: 0,
    wavevectors3d: 0,
    we: 2,
    web: [0, 2, 3],
    whatnot: 0,
    when: 2,
    where: 2,
    which: [0, 2],
    within: [0, 2],
    work: 2,
    would: 2,
    you: 2,
    zack: 3,
    zero: 0,
    "\u03b4": [0, 2],
    "\u03b4m_2": 0,
    "\ud835\udcae_cluster": 0,
  },
  titles: ["pycosmommf package", "API Docs", "Basic Use", "PyCosmoMMF"],
  titleterms: {
    addit: 2,
    api: 1,
    argument: 0,
    author: 3,
    basic: 2,
    code: 2,
    doc: 1,
    filter: 0,
    gener: 2,
    hessian: 0,
    i: 2,
    ii: 2,
    inform: 2,
    modul: 0,
    packag: 0,
    pycosmommf: [0, 3],
    return: 0,
    signatur: 0,
    step: 2,
    submodul: 0,
    tag: 0,
    us: 2,
    usag: 2,
    util: 0,
  },
});
